# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: David Allen Ball
subtitle: IT Professional and Software Engineering Student
description: My web site redesigned with Jekyll.
author:
  name: David Allen Ball
  about: I have been a computer geek for 25 years. I recently resumed undergraduate studies at Radford University, where I am majoring in Software Engineering.
  email: david@daball.me
  github: daball
  facebook: davidallenball
  twitter: daballme
  linkedin: davidball

disqus_shortname: daball

timezone: America/New_York

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
lsi: true

permalink: date
paginate: 8
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: pygments

sass_dir: _sass

gems:
  - jekyll-redirect-from
