services:
  web:
    container_name: daball-me
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:80"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.daball-me.rule=Host(`daball.me`)"
      - "traefik.http.routers.daball-me.entrypoints=websecure"
#      - "traefik.http.routers.daball-me.service=daball-me@docker"
      - "traefik.http.routers.daball-me.tls=true"
      - "traefik.http.routers.daball-me.tls.certresolver=le"
      - "traefik.http.routers.www-daball-me.rule=Host(`www.daball.me`)"
      - "traefik.http.routers.www-daball-me.entrypoints=websecure"
#      - "traefik.http.routers.www-daball-me.service=www-daball-me@docker"
      - "traefik.http.routers.www-daball-me.tls=true"
      - "traefik.http.routers.www-daball-me.tls.certresolver=le"
      - "traefik.http.routers.blog-daball-me.rule=Host(`blog.daball.me`)"
      - "traefik.http.routers.blog-daball-me.entrypoints=websecure"
      - "traefik.http.routers.blog-daball-me.tls=true"
      - "traefik.http.routers.blog-daball-me.tls.certresolver=le"
      - "traefik.http.routers.ccc-daball-me.rule=Host(`ccc.daball.me`)"
      - "traefik.http.routers.ccc-daball-me.entrypoints=websecure"
      - "traefik.http.routers.ccc-daball-me.tls=true"
      - "traefik.http.routers.ccc-daball-me.tls.certresolver=le"
      - "traefik.http.routers.resume-daball-me.rule=Host(`resume.daball.me`)"
      - "traefik.http.routers.resume-daball-me.entrypoints=websecure"
      - "traefik.http.routers.resume-daball-me.tls=true"
      - "traefik.http.routers.resume-daball-me.tls.certresolver=le"

